
# html lang
language: en

# 昵称
avatar: /images/avatar.png
nickname: 牧羊少年

# main menu navigation
menu:
  首页: /
  归档: /archives
  关于: /about


# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/main.css
- /css/media.css

# scripts loaded in the end of the body
scripts:
- /js/resLoader.js
- /js/main.js

# highlight
highlight_style:
  on: true
  inline_code: 5
  code_block: 4
  # Set inline_code to style highlight text
  # Chose a highlight theme for code block
  # 通过 inline_code 切换内置文本高亮样式 Value: 0 - 9 可选
  # 通过 code_block 切换内置代码高亮配色主题  Value: 0 - 4 

# navigations config
navs:
- label: 最新推荐
  list:
    - link: www.36kr.com
      img: /images/navs/36kr.png
      title: 36氪
      desc: 为创业者提供最好的产品和服务
    - link: https://www.v2ex.com
      img: /images/navs/v2ex.png
      title: V2EX
      desc: 一个关于分享和探索的地方
    - link: http://www.arinchina.com
      img: /images/navs/ar.png
      title: ARinChina
      desc: (AR)增强现实(VR)虚拟现实|中国第一AR/VR门户网
    - link: http://store.steampowered.com/
      img: /images/navs/steam.png
      title: Steam
      desc: 全球最大的综合性数字发行平台
- label: 门户社区
  list:
    - title: 掘金
      link: https://juejin.im/
      img: /images/navs/gold.png
      desc: 一个帮助开发者成长的社区
    - title: SegmentFault
      link: https://segmentfault.com/
      img: /images/navs/segmentfault.png
      desc: 一个专注解决变成问题，提高开发者技术的社区
    - title: Stack Overflow
      link: https://stackoverflow.com/
      img: /images/navs/stackoverflow.png
      desc: 编程技术问答网站
    - title: CNode
      link: https://cnodejs.org/
      img: /images/navs/cnodejs.png
      desc: NodeJS专业中文社区
    - title: W3Cplus
      link: https://www.w3cplus.com/
      img: /images/navs/w3cplus.png
      desc: 引领web前沿,打造前端精品教程
    - title: W3Ctech
      link: https://w3ctech.com/
      img: /images/navs/w3ctech.png
      desc: 中国最大的前端技术社区
- label: 代码管理
  list:
    - link: https://github.com/
      img: /images/navs/github.png
      title: GITHUB
      desc: 最大的开源项目git托管平台
    - link: https://coding.net/
      img: /images/navs/coding.png
      title: 码市
      desc: 国内最大的git平台
- label: 框架类库
  list:
    - link: https://cn.vuejs.org/
      img: /images/navs/vue.png
      title: VUE
      desc: 渐进式JavaScript 框架
    - link: https://reactjs.org/
      img: /images/navs/react.png
      title: REACT
      desc: A JavaScript library for building user interfaces
    - link: https://reactnative.cn/
      img: /images/navs/react-native.png
      title: REACT NATIVE
      desc: 使用react构建原生app
    - link: https://www.jquery123.com/
      img: /images/navs/jquery.png
      title: Jquery
      desc: 优秀的前端代码类库
    - link: http://reactivex.io/rxjs/
      img: /images/navs/rxjs.png
      title: rxjs
      desc: The ReactiveX library for JavaScript.
- label: Web框架
  list:
    - link: http://www.expressjs.com.cn/
      img: /images/navs/express.png
      title: EXPRESS
      desc: 基于 Node.js 平台，快速、开放、极简的 web 开发框架
    - link: https://koa.bootcss.com/
      img: /images/navs/koa.png
      title: KOA
      desc: A JavaScript library for building user interfaces
    - link: https://eggjs.org/
      img: /images/navs/egg.svg
      title: EGG
      desc: 为企业级框架和应用而生
    - link: https://thinkjs.org/
      img: /images/navs/thinkjs.png
      title: ThinkJs
      desc: 使用 ES6/7 特性开发 Node.js 项目,支持 TypeScript
    - link: https://zh.nuxtjs.org/
      img: /images/navs/nuxt.png
      title: Nuxt
      desc: VueJS通用应用框架（SSR）
- label: 数据可视化
  list:
    - link: https://antv.alipay.com/zh-cn/index.html#
      img: /images/navs/g2.png
      title: G2
      desc: 蚂蚁金服全新一代数据可视化图表库
    - link: https://d3js.org/
      img: /images/navs/d3.png
      title: D3
      desc: 基于SVG和Canvas的数据可视化js库
    - link: http://www.highcharts.com/
      img: /images/navs/highcharts.png
      title: HighCharts
      desc: Make your data come alive
    - link: http://echarts.baidu.com/
      img: /images/navs/echarts.png
      title: Echart
      desc: 百度数据可视化图标库
- label: 构建打包
  list:
    - link: https://webpack.js.org/
      img: /images/navs/webpack.png
      title: Webpack
      desc: 新一代js模块化构建打包工具
    - link: https://www.gulpjs.com.cn/
      img: /images/navs/gulp.png
      title: Gulp
      desc: 用自动化构建工具增强你的工作流程
- label: 字体图标
  list:
    - link: http://iconfont.cn/
      img: /images/navs/iconfont.png
      title: Icon Font
      desc: 阿里巴巴矢量图标库
    - link: http://www.bootcss.com/p/font-awesome/
      img: /images/navs/font-awesome.png
      title: Font Awesome
      desc: 基于Bootstrap的完美图标字体
- label: 游戏引擎
  list:
    - link: http://www.cocos.com/docs/?type=cocos2d-js#anysdk
      img: /images/navs/cocos2dx.png
      title: cocos2d-js
      desc: cocos游戏引擎js实现
    - link: http://phaser.io/
      img: /images/navs/phaserjs.png
      title: Phaser
      desc: 桌面和移动端的HTML5游戏引擎框架
    - link: https://www.egret.com/
      img: /images/navs/egret.png
      title: 白鹭
      desc: 全球最受欢迎的HTML5游戏引擎
    - link: https://playcanvas.com/explore
      img: /images/navs/playcanvas.png
      title: PlayCanvas
      desc: 3D HTML5 & WebGL 游戏引擎
- label: 在线工具
  list:
    - link: http://www.cocos.com/docs/?type=cocos2d-js#anysdk
      img: /images/navs/tinypng.png
      title: Tiny png
      desc: 在线图片压缩工具
    - link: http://caniuse.com/
      img: /images/navs/caniuse.png
      title: Caniuse
      desc: web前端兼容性查询工具
    - link: http://codepen.io/
      img: /images/navs/codepen.png
      title: Codepen
      desc: 在线web效果测试
    - link: https://resizeappicon.com/
      img: /images/navs/highcharts.png
      title: Icon Resizer
      desc: 一键在线生成各个大小图标
    - link: http://www.unicode.org/emoji/charts/full-emoji-list.html
      img: /images/navs/emoji.png
      title: Emoji编码表
      desc: Full Emoji List, v5.0
- label: 其他推荐
  list:
    - link: https://docs.docker.com/
      img: /images/navs/docker.png
      title: Docker
      desc: 轻松的为任何应用创建一个轻量级的、可移植的、自给自足的容器
    - link: http://guide.daocloud.io/dcs
      img: /images/navs/daocloud.png
      title: Daocloud文档
      desc: Daocloud-企业级云计算领域的创新领导者
    - link: https://developer.mozilla.org/zh-CN/
      img: /images/navs/mdn.png
      title: MDN web文档
      desc: 源于开发者，服务开发者

materials:
- text: Mobi-scroll破解版
  subcode: wqvy
  link: https://pan.baidu.com/s/1pKS7CCF
- text: 字体（平方）
  subcode: qiji
  link: https://pan.baidu.com/s/1cpmjfw
- text: PWA demo
  subcode: 4f36
  link: https://pan.baidu.com/s/1qXEY2wW